Manage posts
CMPUT404W23T05/Social-Distribution-Front-End pull request #14
Opened 2023-03-03 09:45 UTC by jd-lo

### Overview

- Revised cards to support multiple content types (with a footer slot for added versatility)
- On hover, cards will bring up the edit/delete (limited to the Manage Posts page; otherwise w/o slot, will default to username and profile picture of post author)
- Added a popup to make a new post and/or edit an existing
- Added support for Commonmark, plaintext and image posts (jpeg and png)
- Added support for deleting posts (with an accompanying delete prompt
- Made an (unstyled) Manage posts to act as the portal for adding/editing/deleting posts
- Tested and (largely) works against local JSON server

###Known Bugs/Quirks
- Not tested against backend yet due to lack of auth.
- When you edit a post with an image, the image will not render as a thumbnail for whatever reason. I've confirmed that it's passed in as a prop and correctly assigned (the line above the image assignment successfully changes its value) (I've looked into this with little success -- I'm assuming it has to do with component reactivity). However, making a benign change to the source code, then saving it will magically cause the image to appear. Why???
- Right now, alerts pop up when there's an issue with retrieving/posting data to/from server. This will eventually need to be removed.
- Everything is ugly as sin (largely unstyled)

###Screenies :)
![Screenshot from 2023-03-03 01-23-45](https://user-images.githubusercontent.com/90064709/222686887-7e080884-1163-4792-9783-1c5d1c7d819c.png)
![Screenshot from 2023-03-03 01-23-36](https://user-images.githubusercontent.com/90064709/222686952-9755abfd-4727-458e-ba84-22ed8e15c3d9.png)
![Screenshot from 2023-03-03 01-24-14](https://user-images.githubusercontent.com/90064709/222687055-7b33ee50-b223-42c0-91da-942c2f875098.png)

2023-03-03 09:47 UTC, jd-lo commented
Not sure why the check is failing w/ axios. Neither linter nor console has an issue with it.

2023-03-03 09:49 UTC, geofferb commented
> Not sure why the check is failing w/ axios. Neither linter nor console has an issue with it.

See 3ebe20d, you have to add the Axios moduleNameMapper to Jest.

2023-03-08 05:36 UTC, geofferb requested changes
Just the two radio buttons, otherwise it works as stated

2023-03-08 05:36 UTC, geofferb commented on src/components/ManagePost.vue
> +        <input
```suggestion
<input disabled
```
Disable PRIVATE option for now to avoid issues

2023-03-08 05:36 UTC, geofferb commented on src/components/ManagePost.vue
> +        <input
```suggestion
<input disabled
```
Disable FRIENDS option for now to avoid issues

2023-03-08 05:37 UTC, geofferb approved these changes

2023-03-08 05:37 UTC, merged